Auth
sikiritskaya/backend pull request #3
Opened 2022-05-13 09:35 UTC by sikiritskaya

used passport js

2022-05-13 14:10 UTC, alexeykurbako requested changes

2022-05-13 14:10 UTC, alexeykurbako commented on src/Post/postsService.js
> +//import AuthUser from '../User/Auth/AuthUser.js';
remove comment please

2022-05-13 14:10 UTC, alexeykurbako commented on src/User/Auth/authRouter.js
> +authRouter.get('/users/:id', authController.getAllPosts);
remove it please. getAllUsers should be in the users router, getAllPosts should be in posts router

2022-05-13 14:10 UTC, alexeykurbako commented on src/User/Auth/authService/authService.js
> +    async registration(username, password, email) {
rename to signUp

2022-05-13 14:10 UTC, alexeykurbako commented on src/User/Auth/authService/authService.js
> +        const newEmail = await AuthUser.findOne({ email });
I think it could be combined i one request. Just add condition in mongoose request.
Rename variable to existing user

2022-05-13 14:10 UTC, alexeykurbako commented on src/User/Auth/authService/authService.js
> +            console.log(e.message);
write log using logger

2022-05-13 14:10 UTC, alexeykurbako commented on src/User/Auth/authService/authService.js
> +    async login(username, password) {
rename to singIn

2022-05-13 14:10 UTC, alexeykurbako commented on src/User/Auth/authService/authService.js
> +                expiresIn: '24h',
move token expiration into .env file

2022-05-13 14:10 UTC, alexeykurbako commented on src/passport/passport.js
> +        }).catch(done);
I think here should be something like done(null, false, { errors: { 'user': 'Error during getting user' } })

2022-05-13 14:10 UTC, alexeykurbako commented on src/User/Auth/authService/authService.js
> +
remove it

2022-05-13 14:10 UTC, alexeykurbako commented on src/User/Auth/authService/authService.js
> +    }
why do we need it here?

2022-05-13 14:10 UTC, alexeykurbako commented on src/User/Auth/authController.js
> +                    .cookie('token', user.token, { httpOnly: true })
add expiration time here. Cookie should expire the same time as token

2022-05-13 14:10 UTC, alexeykurbako commented on src/Post/postsController.js
> +                res.send('set cookies');
we don't need it here

2022-05-13 14:53 UTC, alexeykurbako commented on src/passport/passport.js
> +    jwtFromRequest: ExtractJwt.fromAuthHeaderAsBearerToken(),
add method that will extract token from cookies

2022-05-13 14:55 UTC, alexeykurbako commented on src/User/Auth/authController.js
> +                return res
let's return here user object instead of token.

2022-05-13 14:59 UTC, alexeykurbako commented on .env
> +ACCESS_TOKEN = 'e3ub8f73js83gjd80os4j'
unused variable

2022-05-13 14:59 UTC, alexeykurbako commented on .env
> +MY_PASS = "Djkjlz1986"
unused variable

2022-05-13 20:44 UTC, sikiritskaya commented on src/Post/postsService.js
> +//import AuthUser from '../User/Auth/AuthUser.js';
removed

2022-05-13 20:45 UTC, sikiritskaya commented on src/User/Auth/authService/authService.js
> +    async registration(username, password, email) {
renamed

2022-05-13 20:47 UTC, sikiritskaya commented on src/User/Auth/authService/authService.js
> +            console.log(e.message);
used logger

2022-05-13 21:05 UTC, sikiritskaya commented on src/User/Auth/authRouter.js
> +authRouter.get('/users/:id', authController.getAllPosts);
removed

2022-05-13 21:09 UTC, sikiritskaya commented on src/User/Auth/authService/authService.js
> +        const newEmail = await AuthUser.findOne({ email });
used one request and renamed variable

2022-05-13 21:15 UTC, sikiritskaya commented on src/User/Auth/authService/authService.js
> +                expiresIn: '24h',
created environment variable

2022-05-13 21:16 UTC, sikiritskaya commented on src/User/Auth/authService/authService.js
> +
removed

2022-05-13 21:17 UTC, sikiritskaya commented on src/passport/passport.js
> +        }).catch(done);
fixed

2022-05-13 21:18 UTC, sikiritskaya commented on src/User/Auth/authService/authService.js
> +    }
removed

2022-05-13 21:18 UTC, sikiritskaya commented on src/Post/postsController.js
> +                res.send('set cookies');
deleted

2022-05-13 21:38 UTC, sikiritskaya commented on .env
> +ACCESS_TOKEN = 'e3ub8f73js83gjd80os4j'
deleted

2022-05-14 10:20 UTC, sikiritskaya commented on src/User/Auth/authController.js
> +                    .cookie('token', user.token, { httpOnly: true })
added expiration date

2022-05-17 08:13 UTC, alexeykurbako commented
remove all commented code please

2022-05-30 16:27 UTC, closed without merging